### ISSUE TITLE
ECS Milestone 2 Feedback (internal)

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/StepsFeedback#6]
Internal feedback on ECS milestone 2 before public announcement.

[Read the internal post](https://octofront.com/content/blog/ecs-milestone2).

**Comment by andrewabest** [comment]
Will leave a trail of suggested edits here:

> This first milestone will create and manage an opinionated CloudFormation template for you

This first milestone will create and manage an ECS service and task definitions for you via CloudFormation, 

> For milestone two of our ECS integration, we are proposing a new step that updates existing ECS services without the need to take ownership of them through a CloudFormation template

For milestone two of our ECS integration, we are proposing a new step that updates existing ECS services without taking ownership of them

>without attempting to own the task definition or service through an associated CloudFormation template.

without attempting to own the task definition or service.

**Comment by andrewabest** [comment]
>This decouples deployment time concerns, such as deploying a new image, from infrastructure concerns, such as creating the initial task definition and service.

This decouples your software release management from your infrastructure release management

**Comment by andrewabest** [comment]
Can we ask an additional question too:

- Can you forsee any challenges that may stop you from using the proposed step with your existing ECS clusters?

**Comment by andrewabest** [comment]
Looks good - easy to interpret, straight forward and to the point.

**Comment by mcasperson** [comment]
Internal feedback is now closed.
